// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectInTerminal(arg1, arg2) {
  return window['go']['sshgate']['Service']['ConnectInTerminal'](arg1, arg2);
}

export function ConnectInTerminalAndTrustHost(arg1, arg2, arg3, arg4) {
  return window['go']['sshgate']['Service']['ConnectInTerminalAndTrustHost'](arg1, arg2, arg3, arg4);
}

export function ConnectInTerminalWithPassword(arg1, arg2, arg3, arg4) {
  return window['go']['sshgate']['Service']['ConnectInTerminalWithPassword'](arg1, arg2, arg3, arg4);
}

export function DeletePasswordForAlias(arg1) {
  return window['go']['sshgate']['Service']['DeletePasswordForAlias'](arg1);
}

export function DeleteSSHHost(arg1) {
  return window['go']['sshgate']['Service']['DeleteSSHHost'](arg1);
}

export function GetActiveTunnels() {
  return window['go']['sshgate']['Service']['GetActiveTunnels']();
}

export function GetSSHConfigFileContent() {
  return window['go']['sshgate']['Service']['GetSSHConfigFileContent']();
}

export function GetSSHHosts() {
  return window['go']['sshgate']['Service']['GetSSHHosts']();
}

export function ReloadSSHHosts() {
  return window['go']['sshgate']['Service']['ReloadSSHHosts']();
}

export function SavePasswordForAlias(arg1, arg2) {
  return window['go']['sshgate']['Service']['SavePasswordForAlias'](arg1, arg2);
}

export function SaveSSHConfigFileContent(arg1) {
  return window['go']['sshgate']['Service']['SaveSSHConfigFileContent'](arg1);
}

export function SaveSSHHost(arg1) {
  return window['go']['sshgate']['Service']['SaveSSHHost'](arg1);
}

export function StartDynamicForward(arg1, arg2, arg3) {
  return window['go']['sshgate']['Service']['StartDynamicForward'](arg1, arg2, arg3);
}

export function StartLocalForward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['sshgate']['Service']['StartLocalForward'](arg1, arg2, arg3, arg4, arg5);
}

export function StopForward(arg1) {
  return window['go']['sshgate']['Service']['StopForward'](arg1);
}
