// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectInTerminal(arg1, arg2) {
  return window['go']['sshgate']['Service']['ConnectInTerminal'](arg1, arg2);
}

export function ConnectInTerminalAndTrustHost(arg1, arg2, arg3, arg4) {
  return window['go']['sshgate']['Service']['ConnectInTerminalAndTrustHost'](arg1, arg2, arg3, arg4);
}

export function ConnectInTerminalWithPassword(arg1, arg2, arg3, arg4) {
  return window['go']['sshgate']['Service']['ConnectInTerminalWithPassword'](arg1, arg2, arg3, arg4);
}

export function CreateAndStartTunnel(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['sshgate']['Service']['CreateAndStartTunnel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeletePassword(arg1) {
  return window['go']['sshgate']['Service']['DeletePassword'](arg1);
}

export function DeleteSSHHost(arg1) {
  return window['go']['sshgate']['Service']['DeleteSSHHost'](arg1);
}

export function DeleteTunnelConfig(arg1) {
  return window['go']['sshgate']['Service']['DeleteTunnelConfig'](arg1);
}

export function DuplicateTunnelConfig(arg1) {
  return window['go']['sshgate']['Service']['DuplicateTunnelConfig'](arg1);
}

export function GetActiveTunnels() {
  return window['go']['sshgate']['Service']['GetActiveTunnels']();
}

export function GetSSHConfigFileContent() {
  return window['go']['sshgate']['Service']['GetSSHConfigFileContent']();
}

export function GetSSHHosts() {
  return window['go']['sshgate']['Service']['GetSSHHosts']();
}

export function GetSavedTunnels() {
  return window['go']['sshgate']['Service']['GetSavedTunnels']();
}

export function ReloadSSHHosts() {
  return window['go']['sshgate']['Service']['ReloadSSHHosts']();
}

export function SavePassword(arg1, arg2) {
  return window['go']['sshgate']['Service']['SavePassword'](arg1, arg2);
}

export function SaveSSHConfigFileContent(arg1) {
  return window['go']['sshgate']['Service']['SaveSSHConfigFileContent'](arg1);
}

export function SaveSSHHost(arg1) {
  return window['go']['sshgate']['Service']['SaveSSHHost'](arg1);
}

export function SaveTunnelConfig(arg1) {
  return window['go']['sshgate']['Service']['SaveTunnelConfig'](arg1);
}

export function Shutdown() {
  return window['go']['sshgate']['Service']['Shutdown']();
}

export function StartTunnelFromConfig(arg1, arg2) {
  return window['go']['sshgate']['Service']['StartTunnelFromConfig'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['sshgate']['Service']['Startup'](arg1);
}

export function StopForward(arg1) {
  return window['go']['sshgate']['Service']['StopForward'](arg1);
}

export function UpdateTunnelsOrder(arg1) {
  return window['go']['sshgate']['Service']['UpdateTunnelsOrder'](arg1);
}

export function VerifyTunnelConfigConnection(arg1, arg2) {
  return window['go']['sshgate']['Service']['VerifyTunnelConfigConnection'](arg1, arg2);
}
