// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {sshtunnel} from '../models';

export function ConnectInTerminal(arg1:string,arg2:boolean):Promise<types.ConnectionResult>;

export function ConnectInTerminalAndTrustHost(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<types.ConnectionResult>;

export function ConnectInTerminalWithPassword(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<types.ConnectionResult>;

export function DeletePasswordForAlias(arg1:string):Promise<void>;

export function DeleteSSHHost(arg1:string):Promise<void>;

export function GetActiveTunnels():Promise<Array<sshtunnel.ActiveTunnelInfo>>;

export function GetSSHConfigFileContent():Promise<string>;

export function GetSSHHosts():Promise<Array<types.SSHHost>>;

export function ReloadSSHHosts():Promise<void>;

export function SavePasswordForAlias(arg1:string,arg2:string):Promise<void>;

export function SaveSSHConfigFileContent(arg1:string):Promise<void>;

export function SaveSSHHost(arg1:types.SSHHost):Promise<void>;

export function StartDynamicForward(arg1:string,arg2:number,arg3:string,arg4:boolean):Promise<string>;

export function StartLocalForward(arg1:string,arg2:number,arg3:string,arg4:number,arg5:string,arg6:boolean):Promise<string>;

export function StopForward(arg1:string):Promise<void>;
