// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {sshtunnel} from '../models';
import {context} from '../models';

export function ConnectInTerminal(arg1:string,arg2:boolean):Promise<types.ConnectionResult>;

export function ConnectInTerminalAndTrustHost(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<types.ConnectionResult>;

export function ConnectInTerminalWithPassword(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<types.ConnectionResult>;

export function CreateAndStartTunnel(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number,arg6:boolean,arg7:string):Promise<string>;

export function DeletePassword(arg1:string):Promise<void>;

export function DeleteSSHHost(arg1:string):Promise<void>;

export function DeleteTunnelConfig(arg1:string):Promise<void>;

export function DuplicateTunnelConfig(arg1:string):Promise<sshtunnel.SavedTunnelConfig>;

export function GetActiveTunnels():Promise<Array<sshtunnel.ActiveTunnelInfo>>;

export function GetSSHConfigFileContent():Promise<string>;

export function GetSSHHosts():Promise<Array<types.SSHHost>>;

export function GetSavedTunnels():Promise<Array<sshtunnel.SavedTunnelConfig>>;

export function ReloadSSHHosts():Promise<void>;

export function SavePassword(arg1:string,arg2:string):Promise<void>;

export function SaveSSHConfigFileContent(arg1:string):Promise<void>;

export function SaveSSHHost(arg1:types.SSHHost,arg2:string):Promise<void>;

export function SaveTunnelConfig(arg1:sshtunnel.SavedTunnelConfig):Promise<void>;

export function Shutdown():Promise<void>;

export function StartTunnelFromConfig(arg1:string,arg2:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopForward(arg1:string):Promise<void>;

export function TrustHostKeyForTunnel(arg1:string):Promise<void>;

export function UpdateHostsOrder(arg1:Array<string>):Promise<void>;

export function UpdateTunnelsOrder(arg1:Array<string>):Promise<void>;

export function VerifyTunnelConfigConnection(arg1:string,arg2:string):Promise<types.ConnectionResult>;
