// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectInTerminal(arg1) {
  return window['go']['backend']['App']['ConnectInTerminal'](arg1);
}

export function Ctx() {
  return window['go']['backend']['App']['Ctx']();
}

export function DeleteConfig(arg1) {
  return window['go']['backend']['App']['DeleteConfig'](arg1);
}

export function DeleteSSHHost(arg1) {
  return window['go']['backend']['App']['DeleteSSHHost'](arg1);
}

export function DeleteSyncPair(arg1) {
  return window['go']['backend']['App']['DeleteSyncPair'](arg1);
}

export function ForceQuit() {
  return window['go']['backend']['App']['ForceQuit']();
}

export function GetActiveTunnels() {
  return window['go']['backend']['App']['GetActiveTunnels']();
}

export function GetConfigs() {
  return window['go']['backend']['App']['GetConfigs']();
}

export function GetSSHConfigFileContent() {
  return window['go']['backend']['App']['GetSSHConfigFileContent']();
}

export function GetSSHHosts() {
  return window['go']['backend']['App']['GetSSHHosts']();
}

export function GetSyncPairs(arg1) {
  return window['go']['backend']['App']['GetSyncPairs'](arg1);
}

export function IsDebug() {
  return window['go']['backend']['App']['IsDebug']();
}

export function IsQuitting() {
  return window['go']['backend']['App']['IsQuitting']();
}

export function LogFromFrontend(arg1) {
  return window['go']['backend']['App']['LogFromFrontend'](arg1);
}

export function Menu(arg1) {
  return window['go']['backend']['App']['Menu'](arg1);
}

export function ReloadSSHHosts() {
  return window['go']['backend']['App']['ReloadSSHHosts']();
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SaveSSHConfigFileContent(arg1) {
  return window['go']['backend']['App']['SaveSSHConfigFileContent'](arg1);
}

export function SaveSSHHost(arg1) {
  return window['go']['backend']['App']['SaveSSHHost'](arg1);
}

export function SaveSyncPair(arg1) {
  return window['go']['backend']['App']['SaveSyncPair'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['backend']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['backend']['App']['SelectFile'](arg1);
}

export function ShowConfirmDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowConfirmDialog'](arg1, arg2);
}

export function ShowErrorDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowErrorDialog'](arg1, arg2);
}

export function ShowInfoDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowInfoDialog'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function StartLocalForward(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['StartLocalForward'](arg1, arg2, arg3, arg4, arg5);
}

export function StartWatching(arg1) {
  return window['go']['backend']['App']['StartWatching'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function StopForward(arg1) {
  return window['go']['backend']['App']['StopForward'](arg1);
}

export function StopWatching(arg1) {
  return window['go']['backend']['App']['StopWatching'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['backend']['App']['TestConnection'](arg1);
}

export function UpdateRemoteFileFromClipboard(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateRemoteFileFromClipboard'](arg1, arg2, arg3, arg4);
}
