// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['backend']['App']['Bootstrap']();
}

export function Ctx() {
  return window['go']['backend']['App']['Ctx']();
}

export function ForceQuit() {
  return window['go']['backend']['App']['ForceQuit']();
}

export function IsDebug() {
  return window['go']['backend']['App']['IsDebug']();
}

export function IsQuitting() {
  return window['go']['backend']['App']['IsQuitting']();
}

export function LogFromFrontend(arg1) {
  return window['go']['backend']['App']['LogFromFrontend'](arg1);
}

export function Menu(arg1) {
  return window['go']['backend']['App']['Menu'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['backend']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['backend']['App']['SelectFile'](arg1);
}

export function ShowConfirmDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowConfirmDialog'](arg1, arg2);
}

export function ShowErrorDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowErrorDialog'](arg1, arg2);
}

export function ShowInfoDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowInfoDialog'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}
