// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {types} from '../models';
import {menu} from '../models';

export function Bootstrap():Promise<void>;

export function Ctx():Promise<context.Context>;

export function DomReady():Promise<void>;

export function ForceQuit():Promise<void>;

export function IsDebug():Promise<boolean>;

export function IsQuitting():Promise<boolean>;

export function LogFromFrontend(arg1:types.LogEntry):Promise<void>;

export function Menu(arg1:menu.Menu):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function ShowConfirmDialog(arg1:string,arg2:string):Promise<string>;

export function ShowErrorDialog(arg1:string,arg2:string):Promise<void>;

export function ShowInfoDialog(arg1:string,arg2:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
