// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {types} from '../models';
import {menu} from '../models';

export function ConnectInTerminal(arg1:string):Promise<void>;

export function Ctx():Promise<context.Context>;

export function DeleteConfig(arg1:string):Promise<void>;

export function DeleteSSHHost(arg1:string):Promise<void>;

export function DeleteSyncPair(arg1:string):Promise<void>;

export function ForceQuit():Promise<void>;

export function GetConfigs():Promise<Array<types.SSHConfig>>;

export function GetSSHConfigFileContent():Promise<string>;

export function GetSSHHosts():Promise<Array<types.SSHHost>>;

export function GetSyncPairs(arg1:string):Promise<Array<types.SyncPair>>;

export function IsDebug():Promise<boolean>;

export function IsQuitting():Promise<boolean>;

export function LogFromFrontend(arg1:types.LogEntry):Promise<void>;

export function Menu(arg1:menu.Menu):Promise<void>;

export function ReloadSSHHosts():Promise<void>;

export function SaveConfig(arg1:types.SSHConfig):Promise<void>;

export function SaveSSHConfigFileContent(arg1:string):Promise<void>;

export function SaveSSHHost(arg1:types.SSHHost):Promise<void>;

export function SaveSyncPair(arg1:types.SyncPair):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function ShowConfirmDialog(arg1:string,arg2:string):Promise<string>;

export function ShowErrorDialog(arg1:string,arg2:string):Promise<void>;

export function ShowInfoDialog(arg1:string,arg2:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartWatching(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopWatching(arg1:string):Promise<void>;

export function TestConnection(arg1:types.SSHConfig):Promise<string>;

export function UpdateRemoteFileFromClipboard(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;
