// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['backend']['App']['Bootstrap']();
}

export function CancelQuitRequest() {
  return window['go']['backend']['App']['CancelQuitRequest']();
}

export function Ctx() {
  return window['go']['backend']['App']['Ctx']();
}

export function DomReady() {
  return window['go']['backend']['App']['DomReady']();
}

export function ForceQuit() {
  return window['go']['backend']['App']['ForceQuit']();
}

export function GetDiagnosticsSnapshot() {
  return window['go']['backend']['App']['GetDiagnosticsSnapshot']();
}

export function GetListeningPorts() {
  return window['go']['backend']['App']['GetListeningPorts']();
}

export function IsDebug() {
  return window['go']['backend']['App']['IsDebug']();
}

export function IsQuitting() {
  return window['go']['backend']['App']['IsQuitting']();
}

export function ListSystemFonts() {
  return window['go']['backend']['App']['ListSystemFonts']();
}

export function LogFromFrontend(arg1) {
  return window['go']['backend']['App']['LogFromFrontend'](arg1);
}

export function Menu(arg1) {
  return window['go']['backend']['App']['Menu'](arg1);
}

export function ReadAppLogTail(arg1) {
  return window['go']['backend']['App']['ReadAppLogTail'](arg1);
}

export function RequestQuit() {
  return window['go']['backend']['App']['RequestQuit']();
}

export function SelectDirectory(arg1) {
  return window['go']['backend']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['backend']['App']['SelectFile'](arg1);
}

export function SendHTTPRequest(arg1) {
  return window['go']['backend']['App']['SendHTTPRequest'](arg1);
}

export function SetupTrayMenu() {
  return window['go']['backend']['App']['SetupTrayMenu']();
}

export function ShowConfirmDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowConfirmDialog'](arg1, arg2);
}

export function ShowErrorDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowErrorDialog'](arg1, arg2);
}

export function ShowInfoDialog(arg1, arg2) {
  return window['go']['backend']['App']['ShowInfoDialog'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function TeardownTrayMenu() {
  return window['go']['backend']['App']['TeardownTrayMenu']();
}
