// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function StartLocalSession():Promise<types.TerminalSessionInfo>;

export function StartSession(arg1:string,arg2:string):Promise<types.TerminalSessionInfo>;
