// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function StartLocalSession(arg1:string):Promise<types.TerminalSessionInfo>;

export function StartRemoteSession(arg1:string,arg2:string,arg3:string):Promise<types.TerminalSessionInfo>;
