// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartSession(arg1, arg2) {
  return window['go']['terminal']['Service']['StartSession'](arg1, arg2);
}
