// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Shutdown() {
  return window['go']['terminal']['Service']['Shutdown']();
}

export function StartLocalSession(arg1) {
  return window['go']['terminal']['Service']['StartLocalSession'](arg1);
}

export function StartRemoteSession(arg1, arg2, arg3) {
  return window['go']['terminal']['Service']['StartRemoteSession'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['terminal']['Service']['Startup'](arg1);
}
