// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConfig(arg1) {
  return window['go']['filesyncer']['Service']['DeleteConfig'](arg1);
}

export function DeleteSyncPair(arg1) {
  return window['go']['filesyncer']['Service']['DeleteSyncPair'](arg1);
}

export function GetActiveWatcherIDs() {
  return window['go']['filesyncer']['Service']['GetActiveWatcherIDs']();
}

export function GetConfigs() {
  return window['go']['filesyncer']['Service']['GetConfigs']();
}

export function GetSyncPairs(arg1) {
  return window['go']['filesyncer']['Service']['GetSyncPairs'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['filesyncer']['Service']['SaveConfig'](arg1);
}

export function SaveSyncPair(arg1) {
  return window['go']['filesyncer']['Service']['SaveSyncPair'](arg1);
}

export function Shutdown() {
  return window['go']['filesyncer']['Service']['Shutdown']();
}

export function StartWatching(arg1) {
  return window['go']['filesyncer']['Service']['StartWatching'](arg1);
}

export function Startup(arg1) {
  return window['go']['filesyncer']['Service']['Startup'](arg1);
}

export function StopWatching(arg1) {
  return window['go']['filesyncer']['Service']['StopWatching'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['filesyncer']['Service']['TestConnection'](arg1);
}

export function UpdateRemoteFileFromClipboard(arg1, arg2, arg3, arg4) {
  return window['go']['filesyncer']['Service']['UpdateRemoteFileFromClipboard'](arg1, arg2, arg3, arg4);
}
