// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function DeleteConfig(arg1:string):Promise<void>;

export function DeleteSyncPair(arg1:string):Promise<void>;

export function GetConfigs():Promise<Array<config.SSHConfig>>;

export function GetSyncPairs(arg1:string):Promise<Array<config.SyncPair>>;

export function SaveConfig(arg1:config.SSHConfig):Promise<void>;

export function SaveSyncPair(arg1:config.SyncPair):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function StartWatching(arg1:string):Promise<void>;

export function StopWatching(arg1:string):Promise<void>;

export function TestConnection(arg1:config.SSHConfig):Promise<string>;

export function UpdateRemoteFileFromClipboard(arg1:string,arg2:string,arg3:string):Promise<void>;
