// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DeleteSyncPair(arg1) {
  return window['go']['main']['App']['DeleteSyncPair'](arg1);
}

export function GetConfigs() {
  return window['go']['main']['App']['GetConfigs']();
}

export function GetSyncPairs(arg1) {
  return window['go']['main']['App']['GetSyncPairs'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveSyncPair(arg1) {
  return window['go']['main']['App']['SaveSyncPair'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function StartWatching(arg1) {
  return window['go']['main']['App']['StartWatching'](arg1);
}

export function StopWatching(arg1) {
  return window['go']['main']['App']['StopWatching'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateRemoteFileFromClipboard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateRemoteFileFromClipboard'](arg1, arg2, arg3, arg4);
}
